# Generated by Django 4.2.2 on 2023-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[(0, 'Воскресенье'), (1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], max_length=1, verbose_name='День недели')),
            ],
        ),
        migrations.AddField(
            model_name='barbers',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='barbershop.tag'),
        ),
    ]
