# Generated by Django 4.2.2 on 2023-10-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbers',
            name='barber_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
