# Generated by Django 4.2.2 on 2023-11-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbers',
            name='barber_name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название услуги'),
        ),
    ]
