# Generated by Django 4.2.2 on 2023-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_alter_barbers_barber_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbers',
            options={'ordering': ['-created'], 'verbose_name': 'Барбера', 'verbose_name_plural': 'Барберы'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-price'], 'verbose_name': 'Стрижка', 'verbose_name_plural': 'Прайс-лист'},
        ),
        migrations.AlterField(
            model_name='barbers',
            name='barber_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='barbers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Был добавлен'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(max_length=200, verbose_name='Название услуги'),
        ),
    ]
