# Generated by Django 4.2.2 on 2023-11-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_alter_barbers_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='days',
            field=models.CharField(choices=[('0', 'Воскресенье'), ('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота')], max_length=1, verbose_name='День недели'),
        ),
    ]
