# Generated by Django 4.2.2 on 2023-11-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_alter_tag_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbers',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='barberss',
            field=models.ManyToManyField(blank=True, to='barbershop.barbers'),
        ),
    ]
