# Generated by Django 4.2.2 on 2023-10-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_alter_barbers_options_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название услуги'),
        ),
    ]
