# Generated by Django 4.2.2 on 2023-10-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0006_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Фото мастера', 'verbose_name_plural': 'Фото мастеров'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_big',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/', verbose_name='Фото большое'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/', verbose_name='Фото маленькое'),
        ),
    ]
