# Generated by Django 4.2.2 on 2023-10-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0008_portfolio_end_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='end_photo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название большого фото'),
        ),
    ]
