# Generated by Django 4.2.2 on 2023-10-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('barber', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=250, null=True)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
