# Generated by Django 4.2.2 on 2023-11-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('day', models.DateField(verbose_name='День')),
                ('time', models.TimeField(verbose_name='Время')),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbers', verbose_name='Барбер')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Клиент')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbershop.price', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-dt'],
            },
        ),
    ]
