# Generated by Django 4.2.2 on 2023-10-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_price'),
        ('appointment', '0002_rename_order_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbers'),
        ),
    ]
