# Generated by Django 4.2.2 on 2023-10-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
