# Generated by Django 4.2.2 on 2023-10-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
