# Generated by Django 4.2.2 on 2023-10-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_alter_barbers_barber_name'),
        ('appointment', '0005_appointment_barber_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='brbr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbers'),
        ),
    ]
