# Generated by Django 4.2.2 on 2023-10-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_brbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='barber_id',
        ),
    ]
