# Generated by Django 4.2.2 on 2023-10-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_alter_price_service'),
        ('appointment', '0009_remove_appointment_brbr_alter_appointment_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbershop.price', verbose_name='Услуга'),
        ),
    ]
